# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Biography"
  url = "#about"
  weight = 5

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 12


[[main]]
  name = "Publications"
  url = "#publications"
  weight = 18

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 25
  
  [[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 33
  
  [[main]]
  name = "Diplomacy"
  url = "#diplomacy"
  weight = 40
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 45

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "https://www.dropbox.com/s/0z87ucj13jckt52/Diana%20D%C3%A1vila%20Gordillo%20CV%20August%202019.pdf?dl=0"
    weight = 70
